---
which-store-info: "{!ENV: MERRITT_STORE_INFO !DEFAULT: store-info}"
store-info:
  baseURI: "{!SSM: store/config/baseURI !DEFAULT: http://store-stage.cdlib.org:35121}"
  servicePattern: "{!SSM: store/config/servicePattern !DEFAULT: http://$hostname.cdlib.org:35121/service/$serviceType}"
  supportURI: mailto:merritt-support@ucop.edu
  verifyOnRead: "{!SSM: store/config/verifyOnRead !DEFAULT: true}"
  verifyOnWrite: "{!SSM: store/config/verifyOnWrite !DEFAULT: true}"
  producerFilter:
    - mrt-erc.txt
    - mrt-eml.txt
    - mrt-dc.xml
    - mrt-delete.txt
    - mrt-dua.txt
    - mrt-dataone-manifest.txt
    - mrt-datacite.xml
    - mrt-embargo.txt
    - mrt-oaidc.xml
    - mrt-provenance.xml
    - stash-wrapper.xml
  archiveNode: 7001
  nodePath: "{!SSM: store/config/nodePath  !DEFAULT: yaml:2}"
  fileLogger:
    messageMaximumLevel: "{!SSM: store/config/log/messageMaximumLevel !DEFAULT: 5}"
    messageMaximumError: "{!SSM: store/config/log/messageMaximumError !DEFAULT: 10}"
    path: "{!ENV: LOG_STORE !DEFAULT: /apps/dpr2store/mrtHomes/store2/}"
    name: store
    qualifier: yyMMdd
    trace: 5
  queueInfo:
    QueueService: "{!SSM: inventory/zoo/queueService !DEFAULT: localhost:2181}"
    QueueLargeWorker: "{!SSM: store/zoo/AccessLarge !DEFAULT: localhost}"
    QueueLockBase: "{!SSM: store/zoo/QueueLockBase !DEFAULT: /mrt.lock}"
    QueueHoldLock: "{!SSM: store/zoo/QueueHoldFile !DEFAULT: access/LargeAccessHold}"
    QueueSizeLimit: "{!SSM: store/zoo/AccessQSize !DEFAULT: 500000000}"
    QueueTimeout: "{!SSM: store/zoo/Timeout !DEFAULT: 40000}"
    LargeAccessHold: "{!SSM: store/zoo/LargeAccessHold !DEFAULT: access/LargeAccessHold}"
    SmallAccessHold: "{!SSM: store/zoo/SmallAccessHold !DEFAULT: access/SmallAccessHold}" 
    
    PollingInterval: "{!SSM: store/config/PollingInterval !DEFAULT: 15}"
    NumThreadsSmall: "{!SSM: store/config/numThreadsSmall !DEFAULT: 5}"
    NumThreadsLarge: "{!SSM: store/config/numThreadsLarge !DEFAULT: 3}"


store-info-docker: &docker
  baseURI: "http://{!ENV: MRT_DOCKER_HOST !DEFAULT: localhost}:8081/store"
  supportURI: mailto:merritt-support@ucop.edu
  verifyOnRead: true
  verifyOnWrite: true
  producerFilter:
    - mrt-erc.txt
    - mrt-eml.txt
    - mrt-dc.xml
    - mrt-delete.txt
    - mrt-dua.txt
    - mrt-dataone-manifest.txt
    - mrt-datacite.xml
    - mrt-embargo.txt
    - mrt-oaidc.xml
    - mrt-provenance.xml
    - stash-wrapper.xml
  archiveNode: 7777
  nodePath: "yaml:2"
  fileLogger:
    messageMaximumLevel: 5
    messageMaximumError: 10
    path: /dpr2store/mrtHomes/
    name: store
    qualifier: yyMMdd
    trace: 5
  queueInfo:
    QueueService: "zoo:2181"
    QueueLargeWorker: "xxxxstore"
    QueueSizeLimit: "600000000"
    QueueLockBase: "/mrt.lock"
    QueueHoldLock: "access/LargeAccessHold"
    QueueHoldFile: "/dpr2store/mrtHomes/AccessHold"
    QueueTimeout: "40000"
    LargeAccessHold: "access/LargeAccessHold"
    SmallAccessHold: "access/SmallAccessHold" 
    PollingInterval: "15"
    NumThreadsSmall: "5"
    NumThreadsLarge: "3"


store-info-dev-docker: 
  <<: *docker
  archiveNode: 5003
